### ISSUE TITLE
modifiers niet gebruikt in css

### ISSUE THREAD

**Issue by Theo-denBlanken** [KickSchutte67/BEM-Opdracht-FRO#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
<li class="nav__item nav--work"><a class="nav__text" href="#">Work</a></li>
            <li class="nav__item nav--home"><a class="nav__text" href="#">Home</a> 
```

URL: https://github.com/KickSchutte67/BEM-Opdracht-FRO/blob/master/BEM/index.html

Feedback: Dan hoef je ze ook niet te maken[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"16ac2e5c835fab6e189cda2f47d6dbcf02ac8773","path":"BEM/index.html","reviewer":"Theo-denBlanken"}')

**Comment by KickSchutte67** [comment]
Ik heb deze code ook veranderd.

Groetjes
